name: flutter_sewoo_usb_printer
description: Flutter plugin for Sewoo USB POS printers using serial connection
version: 0.0.1
homepage: https://github.com/1kl1/flutter_sewoo_usb_printer

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sewoo.flutter_sewoo_usb
        pluginClass: FlutterSewooUsbPlugin